name: build_image_for_test
on:
  push:
    branches:
      - 'test'
      - 'devel'
jobs:
  build-2019:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install zabbix-agent2 -y -s .
      # - name: Syft run
      #   run: |
      #     syft . -v
      #   shell: powershell

  build-2022:
    runs-on: windows-2022
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install zabbix-agent2 -y -s .
      # - name: Syft run
      #   run: |
      #     syft . -v
      #   shell: powershell
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push --source https://www.myget.org/F/public-choco-dev/api/v2/package -k=${{ secrets.MYGET_API_KEY }}
